name: 'Build test release'
on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"

jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ github.token }}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: cancel
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2
      - name: Docker tests
        run: |
          bash ./pack.sh
      - uses: actions/upload-artifact@v2
        name: Upload artifact with the release
        with:
          name: release
          path: ./ps386038.tar.gz
  test_release:
    name: Test packaged release
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: release
      - name: Unpack archive
        run: tar -zxvf ./ps386038.tar.gz
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Test make
        run: cd ps386038 && make
