name: 'Build test release'
on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2
      - name: Docker tests
        run: make test
      - uses: actions/upload-artifact@v2
        name: Upload artifact with the release
        with:
          name: release
          path: ./ps386038.tar.gz
  test_release:
    name: Test packaged release
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: release
      - name: Unpack archive
        run: tar -zxvf ./ps386038.tar.gz
      - name: Test make
        run: make
